name: Deploy Dev Environment (EKS)

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform-check:
    name: Terraform Validate & Plan (PRs + Pushes)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var='aws_region=us-west-2' \
            -var='cluster_name=edguillen-eks-dev' \
            -var='vpc_name=edguillen-vpc-dev' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='private_subnets=["10.0.1.0/24","10.0.2.0/24"]' \
            -var='public_subnets=["10.0.101.0/24","10.0.102.0/24"]' \
            -var='k8s_version=1.30' \
            -out=tfplan

  terraform-apply:
    name: Terraform Apply (Main Branch Only!!)
    needs: terraform-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: dev

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - run: terraform init
      - name: Terraform Apply
        run: |
          terraform apply \
            -var='aws_region=us-west-2' \
            -var='cluster_name=edguillen-eks-dev' \
            -var='vpc_name=edguillen-vpc-dev' \
            -var='vpc_cidr=10.0.0.0/16' \
            -var='private_subnets=["10.0.1.0/24","10.0.2.0/24"]' \
            -var='public_subnets=["10.0.101.0/24","10.0.102.0/24"]' \
            -var='k8s_version=1.30' \
            -auto-approve 

      - name: Output EKS Details
        run: terraform output
