name: Deploy Dev Environment (EKS)

on:
  push:
    branches: [main]
    paths:
      - 'terraform/environments/dev/**'
      - '.github/workflows/deploy-dev.yml'

  pull_request:
    paths:
      - 'terraform/environments/dev/**'

  workflow_dispatch:

jobs:
  terraform-check:
    name: Terraform Validate & Plan (PRs + Pushes)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="default.tfvars" -out=tfplan

  terraform-apply:
    name: Terraform Apply (Main Branch Only!!)
    needs: terraform-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main' && github.event_name == 'push'
    environment: dev

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="default.tfvars"

      - name: Output EKS Details
        run: terraform output
